vms:
  - name: node01.cluster.local
    ip: "192.168.50.101"
    cpu: 2
    memory: 2048
    secondary_disks: 1
  - name: node02.cluster.local
    ip: "192.168.50.102"
    cpu: 2
    memory: 2048
    secondary_disks: 3
  - name: node03.cluster.local
    ip: "192.168.50.103"
    cpu: 2
    memory: 2048
    secondary_disks: 1
  - name: edge.cluster.local
    ip: "192.168.50.199"
    cpu: 2
    memory: 2048
    secondary_disks: 0

disk_size: 15000
disks_folder_path: C:\\Users\\user\\Documents\\disks


# Node01 (18 Go RAM, 6 CPU) :
# Services : ZooKeeper, ResourceManager, HistoryServer,NodeManager
# Node02 (8 Go RAM, 4 CPU) :
# Services : CLDB, FileServer, NFS
# Node03 (20 Go RAM, 5 CPU) :
# Services : Drill, Hive, HiveMetastore, HiveServer2, NodeManager
# Edge Node (4 Go RAM, 2 CPU) :
# Services : Gateway, WebServer
