num_vms: 1
ip_range: "192.168.50"
num_secondary_disks: 2
disk_size: 25600
cpu: 4
memory: 10000
localhost_name: ".cluster.local"
cpu_edge: 2
memory_edge: 2048
localhost_name_edge: ".local"
disks_folder_path: C:\\Users\\user\\Documents\\disks
