# - name: Trouver et copier les fichiers .new et afficher les fichiers traités
#   become: yes
#   shell: |
#     find /opt/mapr -type f -name "*.new" -print0 | while IFS= read -r -d '' file; do
#       cp "$file" "${file%.new}"
#       echo "Copié: $file vers ${file%.new}"
#     done
#   args:
#     executable: /bin/bash
#   register: copy_output

# - name: Afficher le résultat des copies
#   debug:
#     msg: "{{ copy_output.stdout_lines }}"


- name: Exécuter configure.sh
  command: >
    /opt/mapr/server/configure.sh -no-autostart
    -C node01.cluster.local
    -Z node01.cluster.local
    -N bismi.allahi.com
  tags:
    - configure_cluster
    
