- name: Trouver et copier les fichiers .new et afficher les fichiers traités
  become: yes
  shell: |
    find /opt/mapr -type f -name "*.new" -print0 | while IFS= read -r -d '' file; do
      cp "$file" "${file%.new}"
      echo "Copié: $file vers ${file%.new}"
    done
  args:
    executable: /bin/bash
  register: copy_output

- name: Afficher le résultat des copies
  debug:
    msg: "{{ copy_output.stdout_lines }}"


- name: Exécuter configure.sh
  command: >
    /opt/mapr/server/configure.sh -no-autostart
    -C {{ groups['all_nodes'] | join(',') }}
    -Z {{ groups['zookeeper_nodes'] | join(',') }}
    -N {{ cluster_name }}
  when: inventory_hostname in groups['all_nodes']
  tags:
    - configure_cluster
    
