- name: Installer les utilitaires et mettre à jour la liste des paquets disponibles pour Ubuntu
  apt:
    name:
      - syslinux-utils
      - firewalld
      - python
      - nfs-kernel-server
      - openjdk-8-jdk
    state: present
    update_cache: yes
  when: "'Ubuntu' in hostvars[inventory_hostname]['OS']"

- name: Installer les utilitaires et mettre à jour la liste des paquets disponibles pour CentOS
  yum:
    name:
      - syslinux
      - firewalld
      - python
      - nfs-utils
      - java-1.8.0-openjdk-devel   
    state: present
    update_cache: yes
  when: "'CentOS' in hostvars[inventory_hostname]['OS']"

- name: Démarrer et activer firewalld
  systemd:
    name: firewalld
    state: started
    enabled: true
    
- name: Ouvrir les ports nécessaires 
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  with_items: "{{ firewall_ports }}"
