---
- name: Installer history server pour Ubuntu
  apt:
    name: mapr-historyserver
    state: present
  when: "'Ubuntu' in hostvars[inventory_hostname]['OS']"

- name: Installer history server pour Centos
  yum:
    name: mapr-historyserver
    state: present
  when: "'CentOS' in hostvars[inventory_hostname]['OS']"