- name: Installer les utilitaires et mettre à jour la liste des paquets disponibles pour Ubuntu
  apt:
    name:
      - syslinux-utils
      - firewalld
      - python
      - nfs-kernel-server
      - openjdk-8-jdk
    state: present
    update_cache: yes
  when: "'Ubuntu' in hostvars[inventory_hostname]['OS']"

- name: Installer les utilitaires et mettre à jour la liste des paquets disponibles pour CentOS
  yum:
    name:
      - syslinux
      - firewalld
      - python
      - nfs-utils
      - java-1.8.0-openjdk-devel   
    state: present
    update_cache: yes
  when: "'CentOS' in hostvars[inventory_hostname]['OS']"

