    - name: Mettre à jour la liste des paquets disponibles
      apt:
        update_cache: yes
        cache_valid_time: 3600  # Optionnel, limite la fréquence des mises à jour du cache

    - name: Installer les utilitaire
      apt:
        name:
          - syslinux-utils
          - firewalld
          - python
          - nfs-kernel-server
        state: present
 