---
# Fichier principal pour le rôle hadoop_common

- import_tasks: update_hosts.yml

- import_tasks: add_repository_credential.yml

- import_tasks: open_port.yml
# Installer les utilitaires sur tous les nœuds
- include_tasks: install_utilities.yml

- include_tasks: install_base_mapr.yml

- import_tasks: create_user_group.yml

- import_tasks: configure_cluster.yml

- import_tasks: attach_disks.yml
