- name: Démarrer et activer firewalld
  systemd:
    name: firewalld
    state: started
    enabled: true
    
- name: Ouvrir les ports nécessaires pour chaque service
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop: "{{ service_ports[match_group] | default([]) }}"
  when: match_group is defined
  vars:
    match_group: "{{ group_names | map('regex_replace', '_nodes$', '') | map('regex_replace', '^.*_', '') | select('in', service_ports.keys()) | first }}"
