---

- include_tasks: upload_license.yml
  when: inventory_hostname in groups['Licence_node']
 
- include_tasks: configure_cluster.yml

- include_tasks: attach_disks.yml

- include_tasks: start_cluster.yml

- import_tasks: modify_config_file.yml

- import_tasks: validation_test.yml
  tags:
    - validation_test