- name: Adjust zoo.cfg for local node to listen on 0.0.0.0
  lineinfile:
    path: /opt/mapr/zookeeper/zookeeper-3.4.11/conf/zoo.cfg
    regexp: '^(server\.\d+)={{ inventory_hostname }}(:\d+:\d+)$'
    line: '\1=0.0.0.0\2'
    backrefs: yes
  when: inventory_hostname in groups['ZooKeeper_nodes']

- name: restart zookeeper
  service:
    name: mapr-zookeeper
    state: restarted
  when: inventory_hostname in groups['ZooKeeper_nodes']