- name: Configure zoo.cfg to listen on all interfaces or specific host IP
  lineinfile:
    path: /opt/mapr/zookeeper/zookeeper-3.4.11/conf/zoo.cfg
    regexp: '^server.{{ idx }}=.*'
    line: "server.{{ idx }}={{ (inventory_hostname == item) | ternary('0.0.0.0', hostvars[item].ansible_host) }}:2888:3888"
  loop: "{{ groups['ZooKeeper_nodes'] }}"
  loop_control:
    index_var: idx
  when: inventory_hostname in groups['ZooKeeper_nodes']


- name: restart zookeeper
  service:
    name: mapr-zookeeper
    state: restarted
  when: inventory_hostname in groups['ZooKeeper_nodes']