- name: Ensure eth0 is down before starting services
  command: sudo ip link set eth0 down
  ignore_errors: true   
  when: inventory_hostname in groups['ZooKeeper_nodes']

- name: Start MapR-ZooKeeper
  systemd:
    name: mapr-zookeeper
    state: started
  when: inventory_hostname in groups['ZooKeeper_nodes']

- name: Start MapR-Warden
  systemd:
    name: mapr-warden
    state: started


